import type { FoodItem, Category } from "@/lib/types"

export const categories: Category[] = [
  {
    id: 1,
    name: "Burgers",
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: 2,
    name: "Pizzas",
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: 3,
    name: "Salads",
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: 4,
    name: "Drinks",
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: 5,
    name: "Desserts",
    image: "/placeholder.svg?height=200&width=200",
  },
]

export const foodItems: FoodItem[] = [
  {
    id: 1,
    name: "Classic Cheeseburger",
    description: "Beef patty with cheese, lettuce, tomato, and special sauce",
    price: 8.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Burgers",
    featured: true,
  },
  {
    id: 2,
    name: "Double Bacon Burger",
    description: "Two beef patties with bacon, cheese, and BBQ sauce",
    price: 12.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Burgers",
    featured: false,
  },
  {
    id: 3,
    name: "Veggie Burger",
    description: "Plant-based patty with avocado, lettuce, and vegan mayo",
    price: 9.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Burgers",
    featured: false,
  },
  {
    id: 4,
    name: "Margherita Pizza",
    description: "Classic pizza with tomato sauce, mozzarella, and basil",
    price: 14.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Pizzas",
    featured: true,
  },
  {
    id: 5,
    name: "Pepperoni Pizza",
    description: "Pizza with tomato sauce, mozzarella, and pepperoni",
    price: 15.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Pizzas",
    featured: false,
  },
  {
    id: 6,
    name: "BBQ Chicken Pizza",
    description: "Pizza with BBQ sauce, chicken, red onions, and cilantro",
    price: 16.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Pizzas",
    featured: false,
  },
  {
    id: 7,
    name: "Caesar Salad",
    description: "Romaine lettuce with Caesar dressing, croutons, and parmesan",
    price: 7.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Salads",
    featured: false,
  },
  {
    id: 8,
    name: "Greek Salad",
    description: "Mixed greens with feta, olives, tomatoes, and Greek dressing",
    price: 8.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Salads",
    featured: false,
  },
  {
    id: 9,
    name: "Coke",
    description: "Classic cola drink",
    price: 2.49,
    image: "/placeholder.svg?height=300&width=300",
    category: "Drinks",
    featured: false,
  },
  {
    id: 10,
    name: "Iced Tea",
    description: "Refreshing iced tea",
    price: 2.49,
    image: "/placeholder.svg?height=300&width=300",
    category: "Drinks",
    featured: false,
  },
  {
    id: 11,
    name: "Chocolate Brownie",
    description: "Rich chocolate brownie with vanilla ice cream",
    price: 5.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Desserts",
    featured: true,
  },
  {
    id: 12,
    name: "Cheesecake",
    description: "New York style cheesecake with berry compote",
    price: 6.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Desserts",
    featured: true,
  },
]
